package pojo;
// Generated Sep 19, 2013 11:25:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="CATEGORIES"
    ,schema="CAFEITVN"
)
public class Categories  implements java.io.Serializable {


     private int categoryId;
     private String categoryName;

    public Categories() {
    }

    public Categories(int categoryId, String categoryName) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
    }
   
     @Id 
    
    @Column(name="CATEGORY_ID", unique=true, nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    
    @Column(name="CATEGORY_NAME", nullable=false, length=50)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }




}


