package pojo;
// Generated Sep 19, 2013 11:25:08 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name="NEWS"
    ,schema="CAFEITVN"
)
public class News  implements java.io.Serializable {


     private int newsId;
     private int categoriesId;
     private String newsName;
     private String newsTitle;
     private String newsContent;
     private String author;
     private Date date;
     private String imageUrl;
     private Integer status;

    public News() {
    }

	
    public News(int newsId, int categoriesId, Date date) {
        this.newsId = newsId;
        this.categoriesId = categoriesId;
        this.date = date;
    }
    public News(int newsId, int categoriesId, String newsName, String newsTitle, String newsContent, String author, Date date, String imageUrl, Integer status) {
       this.newsId = newsId;
       this.categoriesId = categoriesId;
       this.newsName = newsName;
       this.newsTitle = newsTitle;
       this.newsContent = newsContent;
       this.author = author;
       this.date = date;
       this.imageUrl = imageUrl;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="NEWS_ID", unique=true, nullable=false)
    public int getNewsId() {
        return this.newsId;
    }
    
    public void setNewsId(int newsId) {
        this.newsId = newsId;
    }
    
    @Column(name="CATEGORIES_ID", nullable=false)
    public int getCategoriesId() {
        return this.categoriesId;
    }
    
    public void setCategoriesId(int categoriesId) {
        this.categoriesId = categoriesId;
    }
    
    @Column(name="NEWS_NAME", length=500)
    public String getNewsName() {
        return this.newsName;
    }
    
    public void setNewsName(String newsName) {
        this.newsName = newsName;
    }
    
    @Column(name="NEWS_TITLE", length=32700)
    public String getNewsTitle() {
        return this.newsTitle;
    }
    
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }
    
    @Column(name="NEWS_CONTENT", length=32700)
    public String getNewsContent() {
        return this.newsContent;
    }
    
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent;
    }
    
    @Column(name="AUTHOR", length=100)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATE", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="IMAGE_URL", length=100)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


