package pojo;
// Generated Sep 19, 2013 11:25:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,schema="CAFEITVN"
)
public class Users  implements java.io.Serializable {


     private int userId;
     private String username;
     private String password;
     private String fullname;
     private String email;
     private int role;

    public Users() {
    }

	
    public Users(int userId, String username, String password, int role) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.role = role;
    }
    public Users(int userId, String username, String password, String fullname, String email, int role) {
       this.userId = userId;
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.email = email;
       this.role = role;
    }
   
     @Id 
    
    @Column(name="USER_ID", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="USERNAME", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="PASSWORD", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="FULLNAME", length=100)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="ROLE", nullable=false)
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }




}


